### ISSUE TITLE
_compareObjects()

### ISSUE THREAD

**Issue by skistaddy** [bonfire-js/bonfire.js#3]
```
var diff = require("deep-diff");

var a = {}
var b = {hello: "world"}

function _compareObjects(object1, object2){
    var info = diff(a, b)
    var ret  = []
    for(var i in info){
        var e = info[i]
        ret.push(e.path)
    }
    return ret
}

console.log(_compareObjects(a, b))
```
Works in Node.js

**Comment by skistaddy** [comment]
Should be easy to convert to a NodeLocation

**Comment by skistaddy** [comment]
```
var diff = require("deep-diff");

var a = {}
var b = {hello: "world"}

function _compareObjects(object1, object2){
    var info = diff(a, b)
    var ret  = []
    for(var i in info){
        var e = info[i]
        ret.push(e.path)
    }
    return new NodeLocation(ret)
}

console.log(_compareObjects(a, b))
```

**Comment by skistaddy** [comment]
There, with NodeLocation

**Comment by skistaddy** [comment]
```
var diff = require("deep-diff");

var a = {}
var b = {hello: "world"}

function _compareObjects(object1, object2){
    var info = diff(object1, object2)
    var ret  = []
    for(var i in info){
        var e = info[i]
        ret.push(e.path)
    }
    return new NodeLocation(ret)
}

console.log(_compareObjects(a, b))
```

**Comment by davidnagli** [comment]
```
let resultLocationArray = diffFunction(originalObject, updatedObject)[0].locationArray
                                                                            ^

TypeError: Cannot read property 'locationArray' of undefined
    at testDiffer (/Users/davidnagli/Desktop/coding/projects/bonfire/temp/x.js:57:77)
    at Object.<anonymous> (/Users/davidnagli/Desktop/coding/projects/bonfire/temp/x.js:104:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)

```

**Comment by davidnagli** [comment]
For some reason your function your function is returning only a single NodeLocation containing an array of arrays as it’s initialLocationArray

**Comment by davidnagli** [comment]
I fixed it!!!

```javascript
function _compareObjects(object1, object2){
    var info = diff(object1, object2)
    var ret  = []
    for(var i in info){
        var e = info[i]
        ret.push(new NodeLocation(e.path))
    }
    return ret
}
```

**Comment by skistaddy** [comment]
Works
